name: tikHomepage Action

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@source

    - name: Build and Deploy
      uses: JamesIves/github-pages-deploy-action@master
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }} 
        BRANCH: gh-pages
        FOLDER: build
        BUILD_SCRIPT: npm install && npm run build

    # - name: Build
    #   run: npm i && npm run build
      
    # - name: Deploy
    #   uses: JamesIves/github-pages-deploy-action@master
    #   env:
    #     ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
    #     BRANCH: master
    #     FOLDER: build
