name: tikHomepage Action

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@sourceCode
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: build and deploy
      uses: JamesIves/github-pages-deploy-action@master
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BRANCH: master
        FOLDER: build
        BUILD_SCRIPT: npm install && npm run build
        
#     - name: npm install, build
#       run: |
#         npm i
#         npm run build
#     - name: Deploy
#       run: |
#         cd ./dist
#         git clone 